default-resources:
    slurm_partition: "componc_cpu"
    slurm_account: "greenbab"
    runtime: 40 # 2hrs
    mem_mb: 64000
    # mem_mb_per_cpu: 64000 #16GB
    # mem_mb_per_cpu: 16384 #16GB #low
    cpus_per_task: 12
    nodes: 1
executor: slurm

set-resources:
    pod5:
        slurm_partition: "componc_cpu" # deviating partition for this rule
        slurm_account: "greenbab"
        nodes: 1
        runtime: 1440
        # slurm_extra: "'--gpus=4'"
        mem_mb_per_cpu: 65536
        cpus_per_task: 12
    pod5_inspect_debug:
        slurm_partition: "componc_cpu" # deviating partition for this rule
        slurm_account: "greenbab"
        nodes: 1
        runtime: 1440
        # slurm_extra: "'--gpus=4'"
        mem_mb_per_cpu: 65536
        cpus_per_task: 12
    mod_bases:
        slurm_partition: "componc_gpu" # deviating partition for this rule
        slurm_account: "greenbab"
        nodes: 1
        runtime: 1440
        slurm_extra: "'--gpus=4'"
        mem_mb_per_cpu: 24800
        cpus_per_task: 16
    dorado_summary:
        slurm_partition: "componc_cpu" # deviating partition for this rule
        slurm_account: "greenbab"
        nodes: 1
        runtime: 120
        mem_mb_per_cpu: 16800
        cpus_per_task: 8
    mark_duplicates:
        slurm_partition: "componc_cpu" # deviating partition for this rule 
        slurm_account: "greenbab"
        nodes: 1
        runtime: 1000
        # runtime: 240
        # slurm_extra: "'--gres gpu:4'"
        mem_mb_per_cpu: 24800
        cpus_per_task: 16
    merge_bams:
        slurm_partition: "componc_cpu" # deviating partition for this rule 
        slurm_account: "greenbab"
        nodes: 1
        runtime: 1400
        mem_mb_per_cpu: 14800
        cpus_per_task: 16
    modkit:
        slurm_partition: "componc_cpu" # deviating partition for this rule 
        slurm_account: "greenbab"
        nodes: 1
        runtime: 1000 
        # runtime: 360 
        # slurm_extra: "'--gres gpu:4'"
        mem_mb_per_cpu: 24800
        cpus_per_task: 16
    # placeeholder_rule:
    #     slurm_partition: "componc_gpu" # deviating partition for this rule 
    #     slurm_account: "greenbab"
    #     runtime: 240 # 1 hour
    #     slurm_extra: "'--gres gpu:4'"
    #     mem_mb_per_cpu: 24800
    #     cpus_per_task: 24
#snakemake run options
keep-incomplete: True
# --singularity-args: "\"--bind /data1/greenbab\""
# use-conda: True
jobs: 10
keep-going: True
# rerun-incomplete: True
# restart-times: 2
printshellcmds: True
# shadow-prefix: /scratch/ntpierce
latency-wait: 360
# forceall: True
#cmd options
#https://snakemake.readthedocs.io/en/stable/executing/cli.html
#https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/slurm.html